server:
  port: 31000
spring:
  application:
    name: xc-service-manage-cms-client
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017
      database: xc_cms
  freemarker:
    settings:
      template_update_delay: 0
  rabbitmq:
    host: 132.232.117.84
    username: guest
    password: guest
    template:
      retry:
        enabled: true
    port: 5672
xuecheng:
  mq:
    #cms客户端监控的队列名称（不同的客户端监控的队列不能重复）
    queue: queue_cms_postpage_01
    routingKey: 5a751fab6abb5044e0d19ea1	#此routingKey为门户站点ID